### ISSUE TITLE
Facing Error :  resource_management.core.exceptions.Fail: Execution of '/usr/bin/yum -d 0 -e 0 -y install dsc21' returned 1. Error: Nothing to do

### ISSUE THREAD

**Issue by raamvirus** [Symantec/ambari-cassandra-service#12]
While Deploying Via Ambari .Facing the below Error.

stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/CASSANDRA/package/scripts/cassandra_master.py", line 60, in <module>
    Cassandra_Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 216, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/CASSANDRA/package/scripts/cassandra_master.py", line 30, in install
    self.install_packages(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 364, in install_packages
    Package(name)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 157, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 152, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 118, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 43, in action_install
    self.install_package(package_name, self.resource.use_repos)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/yumrpm.py", line 50, in install_package
    shell.checked_call(cmd, sudo=True, logoutput=self.get_logoutput())
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 68, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 86, in checked_call
    return _call(command, logoutput, True, cwd, env, preexec_fn, user, wait_for_finish, timeout, path, sudo, on_new_line)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 204, in _call
    raise Fail(err_msg)
resource_management.core.exceptions.Fail: Execution of '/usr/bin/yum -d 0 -e 0 -y install dsc21' returned 1. Error: Nothing to do
 stdout:
2017-03-09 16:22:10,777 - Group['hadoop'] {'ignore_failures': False}
2017-03-09 16:22:10,778 - Group['users'] {'ignore_failures': False}
2017-03-09 16:22:10,778 - Group['spark'] {'ignore_failures': False}
2017-03-09 16:22:10,779 - User['oozie'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['users']}
2017-03-09 16:22:10,779 - User['hive'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,780 - User['ambari-qa'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['users']}
2017-03-09 16:22:10,781 - User['flume'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,781 - User['hdfs'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,782 - User['storm'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,782 - User['spark'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,783 - User['smoke'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,784 - User['mapred'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,784 - User['hbase'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,785 - User['cassandra'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,786 - User['tez'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['users']}
2017-03-09 16:22:10,786 - User['zookeeper'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,787 - User['kafka'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,787 - User['falcon'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,788 - User['sqoop'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,789 - User['yarn'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,789 - User['hcat'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,790 - User['ams'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,791 - User['atlas'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,792 - File['/var/lib/ambari-agent/data/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-03-09 16:22:10,796 - Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-03-09 16:22:10,825 - Skipping Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] due to not_if
2017-03-09 16:22:10,825 - Directory['/tmp/hbase-hbase'] {'owner': 'hbase', 'recursive': True, 'mode': 0775, 'cd_access': 'a'}
2017-03-09 16:22:10,826 - File['/var/lib/ambari-agent/data/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-03-09 16:22:10,828 - Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase'] {'not_if': '(test $(id -u hbase) -gt 1000) || (false)'}
2017-03-09 16:22:10,834 - Skipping Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase'] due to not_if
2017-03-09 16:22:10,834 - Group['hdfs'] {'ignore_failures': False}
2017-03-09 16:22:10,834 - User['hdfs'] {'ignore_failures': False, 'groups': ['hadoop', 'hdfs']}
2017-03-09 16:22:10,836 - Directory['/etc/hadoop'] {'mode': 0755}
2017-03-09 16:22:10,851 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-03-09 16:22:10,869 - Repository['HDP-2.3'] {'base_url': 'http://public-repo-1.hortonworks.com/HDP-LABS/Projects/Dal-Preview/2.3.0.0-3/centos6/', 'action': ['create'], 'components': ['HDP', 'main'], 'repo_template': 'repo_suse_rhel.j2', 'repo_file_name': 'HDP', 'mirror_list': None}
2017-03-09 16:22:10,879 - File['/etc/yum.repos.d/HDP.repo'] {'content': Template('/usr/lib/ambari-server/lib/resource_management/libraries/providers/../data/repo_suse_rhel.j2')}
2017-03-09 16:22:10,880 - Repository['HDP-UTILS-1.1.0.20'] {'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos6', 'action': ['create'], 'components': ['HDP-UTILS', 'main'], 'repo_template': 'repo_suse_rhel.j2', 'repo_file_name': 'HDP-UTILS', 'mirror_list': None}
2017-03-09 16:22:10,883 - File['/etc/yum.repos.d/HDP-UTILS.repo'] {'content': Template('/usr/lib/ambari-server/lib/resource_management/libraries/providers/../data/repo_suse_rhel.j2')}
2017-03-09 16:22:10,884 - Package['unzip'] {}
2017-03-09 16:22:11,837 - Skipping installation of existing package unzip
2017-03-09 16:22:11,837 - Package['curl'] {}
2017-03-09 16:22:12,010 - Skipping installation of existing package curl
2017-03-09 16:22:12,010 - Package['hdp-select'] {}
2017-03-09 16:22:12,116 - Skipping installation of existing package hdp-select
Install
2017-03-09 16:22:12,254 - Package['dsc21'] {}
2017-03-09 16:22:12,425 - Installing package dsc21 ('/usr/bin/yum -d 0 -e 0 -y install dsc21')

**Comment by ajak6** [comment]
Can you check your yum repo that you have a repo where your Cassandra rpm is present?

On Mar 9, 2017, at 8:25 AM, raamvirus <notifications@github.com<mailto:notifications@github.com>> wrote:


While Deploying Via Ambari .Facing the below Error.

stderr:
Traceback (most recent call last):
File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/CASSANDRA/package/scripts/cassandra_master.py", line 60, in
Cassandra_Master().execute()
File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 216, in execute
method(env)
File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/CASSANDRA/package/scripts/cassandra_master.py", line 30, in install
self.install_packages(env)
File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 364, in install_packages
Package(name)
File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 157, in init
self.env.run()
File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 152, in run
self.run_action(resource, action)
File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 118, in run_action
provider_action()
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/init.py", line 43, in action_install
self.install_package(package_name, self.resource.use_repos)
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/yumrpm.py", line 50, in install_package
shell.checked_call(cmd, sudo=True, logoutput=self.get_logoutput())
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 68, in inner
result = function(command, **kwargs)
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 86, in checked_call
return _call(command, logoutput, True, cwd, env, preexec_fn, user, wait_for_finish, timeout, path, sudo, on_new_line)
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 204, in _call
raise Fail(err_msg)
resource_management.core.exceptions.Fail: Execution of '/usr/bin/yum -d 0 -e 0 -y install dsc21' returned 1. Error: Nothing to do
stdout:
2017-03-09 16:22:10,777 - Group['hadoop'] {'ignore_failures': False}
2017-03-09 16:22:10,778 - Group['users'] {'ignore_failures': False}
2017-03-09 16:22:10,778 - Group['spark'] {'ignore_failures': False}
2017-03-09 16:22:10,779 - User['oozie'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['users']}
2017-03-09 16:22:10,779 - User['hive'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,780 - User['ambari-qa'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['users']}
2017-03-09 16:22:10,781 - User['flume'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,781 - User['hdfs'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,782 - User['storm'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,782 - User['spark'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,783 - User['smoke'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,784 - User['mapred'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,784 - User['hbase'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,785 - User['cassandra'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,786 - User['tez'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['users']}
2017-03-09 16:22:10,786 - User['zookeeper'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,787 - User['kafka'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,787 - User['falcon'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,788 - User['sqoop'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,789 - User['yarn'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,789 - User['hcat'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,790 - User['ams'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,791 - User['atlas'] {'gid': 'hadoop', 'ignore_failures': False, 'groups': ['hadoop']}
2017-03-09 16:22:10,792 - File['/var/lib/ambari-agent/data/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-03-09 16:22:10,796 - Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-03-09 16:22:10,825 - Skipping Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] due to not_if
2017-03-09 16:22:10,825 - Directory['/tmp/hbase-hbase'] {'owner': 'hbase', 'recursive': True, 'mode': 0775, 'cd_access': 'a'}
2017-03-09 16:22:10,826 - File['/var/lib/ambari-agent/data/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-03-09 16:22:10,828 - Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase'] {'not_if': '(test $(id -u hbase) -gt 1000) || (false)'}
2017-03-09 16:22:10,834 - Skipping Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase'] due to not_if
2017-03-09 16:22:10,834 - Group['hdfs'] {'ignore_failures': False}
2017-03-09 16:22:10,834 - User['hdfs'] {'ignore_failures': False, 'groups': ['hadoop', 'hdfs']}
2017-03-09 16:22:10,836 - Directory['/etc/hadoop'] {'mode': 0755}
2017-03-09 16:22:10,851 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-03-09 16:22:10,869 - Repository['HDP-2.3'] {'base_url': 'http://public-repo-1.hortonworks.com/HDP-LABS/Projects/Dal-Preview/2.3.0.0-3/centos6/', 'action': ['create'], 'components': ['HDP', 'main'], 'repo_template': 'repo_suse_rhel.j2', 'repo_file_name': 'HDP', 'mirror_list': None}
2017-03-09 16:22:10,879 - File['/etc/yum.repos.d/HDP.repo'] {'content': Template('/usr/lib/ambari-server/lib/resource_management/libraries/providers/../data/repo_suse_rhel.j2')}
2017-03-09 16:22:10,880 - Repository['HDP-UTILS-1.1.0.20'] {'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos6', 'action': ['create'], 'components': ['HDP-UTILS', 'main'], 'repo_template': 'repo_suse_rhel.j2', 'repo_file_name': 'HDP-UTILS', 'mirror_list': None}
2017-03-09 16:22:10,883 - File['/etc/yum.repos.d/HDP-UTILS.repo'] {'content': Template('/usr/lib/ambari-server/lib/resource_management/libraries/providers/../data/repo_suse_rhel.j2')}
2017-03-09 16:22:10,884 - Package['unzip'] {}
2017-03-09 16:22:11,837 - Skipping installation of existing package unzip
2017-03-09 16:22:11,837 - Package['curl'] {}
2017-03-09 16:22:12,010 - Skipping installation of existing package curl
2017-03-09 16:22:12,010 - Package['hdp-select'] {}
2017-03-09 16:22:12,116 - Skipping installation of existing package hdp-select
Install
2017-03-09 16:22:12,254 - Package['dsc21'] {}
2017-03-09 16:22:12,425 - Installing package dsc21 ('/usr/bin/yum -d 0 -e 0 -y install dsc21')
