### ISSUE TITLE
Trying to start Cassandra service over Ambari server Web UI

### ISSUE THREAD

**Issue by alzameelan** [Symantec/ambari-cassandra-service#14]
Hello. 
i'm trying to use cassandra in ambari-server 
i'm Usinig vagrant tool, OS Ubuntu 14.04 
i added the service to ambari-server but it stays in yellow,
![unbenannt](https://user-images.githubusercontent.com/31002294/29613680-783cd994-8807-11e7-8f3a-20be52c9fb4b.PNG)
![unbenannt1](https://user-images.githubusercontent.com/31002294/29613681-783ef062-8807-11e7-9973-45817a965411.PNG)
![unbenannt2](https://user-images.githubusercontent.com/31002294/29613682-784041ce-8807-11e7-99b8-c6727789304c.PNG)

can some help me to got cassandra running on Ambari-server!

**Comment by ajak6** [comment]
Can you goto to ambari server host and add the error. If you dont see any error check cassandra logs on the host. What i see is you provided 3 seed nodes but you are installing cassandra only on 1 host.

On Aug 23, 2017, at 4:33 AM, alzameelan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello.
i'm trying to use cassandra in ambari-server
i'm Usinig vagrant tool, OS Ubuntu 14.04
i added the service to ambari-server but it stays in yellow,
[unbenannt]<https://user-images.githubusercontent.com/31002294/29613680-783cd994-8807-11e7-8f3a-20be52c9fb4b.PNG>
[unbenannt1]<https://user-images.githubusercontent.com/31002294/29613681-783ef062-8807-11e7-9973-45817a965411.PNG>
[unbenannt2]<https://user-images.githubusercontent.com/31002294/29613682-784041ce-8807-11e7-99b8-c6727789304c.PNG>

can some help me to got cassandra running on Ambari-server!

**Comment by alzameelan** [comment]
i really have only two nodes one of them is ambar-server : 192.168.14.101.  Hostname: u1401.ambari.apache.org, the second one is amabri-agent: 192.168.14.102.  Hostname: u1402.ambari.apache.org. 

i installed ambari-cassandra-service on both of them , i also installed cassandra separately on both of them i will try to get the error ASAP.

**Comment by alzameelan** [comment]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/cassandra_master.py", line 60, in <module>
    Cassandra_Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/cassandra_master.py", line 27, in install
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/params.py", line 16, in <module>
    from resource_management.libraries.functions.version import format_hdp_stack_version, compare_versions
ImportError: cannot import name format_hdp_stack_version




2017-08-24 14:31:23,502 - Stack Feature Version Info: stack_version=2.6, version=2.6.1.0-129, current_cluster_version=2.6.1.0-129 -> 2.6.1.0-129
2017-08-24 14:31:23,542 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
User Group mapping (user_group) is missing in the hostLevelParams
2017-08-24 14:31:23,575 - Group['hadoop'] {}
2017-08-24 14:31:23,645 - Group['users'] {}
2017-08-24 14:31:23,646 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,726 - User['cassandra'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,729 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,730 - User['oozie'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-08-24 14:31:23,733 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-08-24 14:31:23,734 - User['smoke'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,735 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,737 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,761 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-08-24 14:31:23,764 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-08-24 14:31:23,973 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-08-24 14:31:24,642 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] due to not_if
2017-08-24 14:31:24,643 - Group['hdfs'] {}
2017-08-24 14:31:24,644 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': [u'hadoop', u'hdfs']}
2017-08-24 14:31:24,645 - FS Type: 
2017-08-24 14:31:24,646 - Directory['/etc/hadoop'] {'mode': 0755}
2017-08-24 14:31:25,005 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-08-24 14:31:25,049 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2017-08-24 14:31:25,180 - Initializing 2 repositories
2017-08-24 14:31:25,182 - Repository['HDP-2.6'] {'base_url': 'http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.6.1.0', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': '{{package_type}} {{base_url}} {{components}}', 'repo_file_name': 'HDP', 'mirror_list': None}
2017-08-24 14:31:25,429 - File['/tmp/tmpu9pdXD'] {'content': 'deb http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.6.1.0 HDP main'}
2017-08-24 14:31:25,467 - Writing File['/tmp/tmpu9pdXD'] because contents don't match
2017-08-24 14:31:25,591 - File['/tmp/tmpztVJ0U'] {'content': StaticFile('/etc/apt/sources.list.d/HDP.list')}
2017-08-24 14:31:25,629 - Writing File['/tmp/tmpztVJ0U'] because contents don't match
2017-08-24 14:31:25,646 - Repository['HDP-UTILS-1.1.0.21'] {'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu14', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': '{{package_type}} {{base_url}} {{components}}', 'repo_file_name': 'HDP-UTILS', 'mirror_list': None}
2017-08-24 14:31:25,661 - File['/tmp/tmpyQjjEE'] {'content': 'deb http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu14 HDP-UTILS main'}
2017-08-24 14:31:25,667 - Writing File['/tmp/tmpyQjjEE'] because contents don't match
2017-08-24 14:31:25,708 - File['/tmp/tmpWtEJtK'] {'content': StaticFile('/etc/apt/sources.list.d/HDP-UTILS.list')}
2017-08-24 14:31:25,773 - Writing File['/tmp/tmpWtEJtK'] because contents don't match
2017-08-24 14:31:25,889 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-08-24 14:31:26,578 - Skipping installation of existing package unzip
2017-08-24 14:31:26,586 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-08-24 14:31:27,007 - Skipping installation of existing package curl
2017-08-24 14:31:27,020 - Package['hdp-select'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-08-24 14:31:27,376 - Skipping installation of existing package hdp-select

Command failed after 1 tries

**Comment by alzameelan** [comment]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/clients.py", line 38, in <module>
    clients().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
    method(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 810, in restart
    self.install(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/clients.py", line 32, in install
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/params.py", line 16, in <module>
    from resource_management.libraries.functions.version import format_hdp_stack_version, compare_versions
ImportError: cannot import name format_hdp_stack_version
