### ISSUE TITLE
Error when install cassandra 2.1 on hdp 2.6

### ISSUE THREAD

**Issue by dangkhoa12pfiev3** [Symantec/ambari-cassandra-service#16]
Hello.
I'm trying to use cassandra in ambari-server.
I installed ambari-server and some nodes on real machines instead of using HDPSandbox.
I'm using Ubuntu 16.04 as my OS. The version of cluster is HDP - 2.6.3.0
I followed your instructions to install cassandra. At the final step, the installation was failed because of this error of Cluster Nodes Install
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/cassandra_master.py", line 60, in <module>
    Cassandra_Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 367, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/cassandra_master.py", line 30, in install
    self.install_packages(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 813, in install_packages
    retry_count=agent_stack_retry_count)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 53, in action_install
    self.install_package(package_name, self.resource.use_repos, self.resource.skip_repos)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/apt.py", line 75, in wrapper
    return function_to_decorate(self, name, *args[2:])
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/apt.py", line 376, in install_package
    self.checked_call_with_retries(cmd, sudo=True, env=INSTALL_CMD_ENV, logoutput=self.get_logoutput())
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 251, in checked_call_with_retries
    return self._call_with_retries(cmd, is_checked=True, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 268, in _call_with_retries
    code, out = func(cmd, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 303, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21' returned 100. Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dsc21
stdout:   /var/lib/ambari-agent/data/output-191.txt

2017-12-04 09:59:06,860 - Stack Feature Version Info: Cluster Stack=2.6, Command Stack=None, Command Version=None -> 2.6
2017-12-04 09:59:06,865 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-12-04 09:59:06,866 - Group['hdfs'] {}
2017-12-04 09:59:06,866 - Group['hadoop'] {}
2017-12-04 09:59:06,867 - Group['users'] {}
2017-12-04 09:59:06,867 - User['infra-solr'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,868 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,868 - User['cassandra'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,869 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,869 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users'], 'uid': None}
2017-12-04 09:59:06,870 - User['smoke'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,870 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hdfs'], 'uid': None}
2017-12-04 09:59:06,871 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,871 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,872 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-12-04 09:59:06,873 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-12-04 09:59:06,876 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2017-12-04 09:59:06,877 - Group['hdfs'] {}
2017-12-04 09:59:06,877 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': ['hdfs', u'hdfs']}
2017-12-04 09:59:06,878 - FS Type: 
2017-12-04 09:59:06,878 - Directory['/etc/hadoop'] {'mode': 0755}
2017-12-04 09:59:06,891 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-12-04 09:59:06,891 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2017-12-04 09:59:06,905 - Repository['HDP-2.6-repo-1'] {'append_to_file': False, 'base_url': 'http://public-repo-1.hortonworks.com/HDP/ubuntu16/2.x/updates/2.6.3.0', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': '{{package_type}} {{base_url}} {{components}}', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2017-12-04 09:59:06,912 - File['/tmp/tmp6cMkrY'] {'content': 'deb http://public-repo-1.hortonworks.com/HDP/ubuntu16/2.x/updates/2.6.3.0 HDP main'}
2017-12-04 09:59:06,912 - Writing File['/tmp/tmp6cMkrY'] because contents don't match
2017-12-04 09:59:06,912 - File['/tmp/tmpgvtRaA'] {'content': StaticFile('/etc/apt/sources.list.d/ambari-hdp-1.list')}
2017-12-04 09:59:06,913 - Writing File['/tmp/tmpgvtRaA'] because contents don't match
2017-12-04 09:59:06,913 - File['/etc/apt/sources.list.d/ambari-hdp-1.list'] {'content': StaticFile('/tmp/tmp6cMkrY')}
2017-12-04 09:59:06,913 - Writing File['/etc/apt/sources.list.d/ambari-hdp-1.list'] because contents don't match
2017-12-04 09:59:06,913 - checked_call[['apt-get', 'update', '-qq', '-o', u'Dir::Etc::sourcelist=sources.list.d/ambari-hdp-1.list', '-o', 'Dir::Etc::sourceparts=-', '-o', 'APT::Get::List-Cleanup=0']] {'sudo': True, 'quiet': False}
2017-12-04 09:59:07,040 - checked_call returned (0, '')
2017-12-04 09:59:07,041 - Repository['HDP-UTILS-1.1.0.21-repo-1'] {'append_to_file': True, 'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu16', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': '{{package_type}} {{base_url}} {{components}}', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2017-12-04 09:59:07,043 - File['/tmp/tmpPBUb6S'] {'content': 'deb http://public-repo-1.hortonworks.com/HDP/ubuntu16/2.x/updates/2.6.3.0 HDP main\ndeb http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu16 HDP-UTILS main'}
2017-12-04 09:59:07,043 - Writing File['/tmp/tmpPBUb6S'] because contents don't match
2017-12-04 09:59:07,044 - File['/tmp/tmpbGWklO'] {'content': StaticFile('/etc/apt/sources.list.d/ambari-hdp-1.list')}
2017-12-04 09:59:07,044 - Writing File['/tmp/tmpbGWklO'] because contents don't match
2017-12-04 09:59:07,044 - File['/etc/apt/sources.list.d/ambari-hdp-1.list'] {'content': StaticFile('/tmp/tmpPBUb6S')}
2017-12-04 09:59:07,044 - Writing File['/etc/apt/sources.list.d/ambari-hdp-1.list'] because contents don't match
2017-12-04 09:59:07,045 - checked_call[['apt-get', 'update', '-qq', '-o', u'Dir::Etc::sourcelist=sources.list.d/ambari-hdp-1.list', '-o', 'Dir::Etc::sourceparts=-', '-o', 'APT::Get::List-Cleanup=0']] {'sudo': True, 'quiet': False}
2017-12-04 09:59:07,178 - checked_call returned (0, 'W: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu16/dists/HDP-UTILS/InRelease: Signature by key DF52ED4F7A3A5882C0994C66B9733A7A07513CAD uses weak digest algorithm (SHA1)')
2017-12-04 09:59:07,178 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,194 - Skipping installation of existing package unzip
2017-12-04 09:59:07,194 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,209 - Skipping installation of existing package curl
2017-12-04 09:59:07,209 - Package['hdp-select'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,224 - Skipping installation of existing package hdp-select
2017-12-04 09:59:07,228 - The repository with version 2.6.3.0-235 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2017-12-04 09:59:07,232 - Skipping stack-select on CASSANDRA because it does not exist in the stack-select package structure.
Install
2017-12-04 09:59:07,378 - Package['dsc21'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,394 - Installing package dsc21 ('/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21')
**2017-12-04 09:59:08,682 - Execution of '/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21' returned 100. Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dsc21
2017-12-04 09:59:08,682 - Failed to install package dsc21. Executing '/usr/bin/apt-get update -qq'
2017-12-04 09:59:10,008 - Retrying to install package dsc21 after 30 seconds
2017-12-04 09:59:40,218 - The repository with version 2.6.3.0-235 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2017-12-04 09:59:40,223 - Skipping stack-select on CASSANDRA because it does not exist in the stack-select package structure.**

Command failed after 1 tries

Can someone help me to fix it ?

**Comment by ajak6** [comment]
From the output the problem is the name of rpm in your repo is different than what it is trying to install. Change the name of the Cassandra rpm in xml file.

On Dec 4, 2017, at 2:22 AM, dangkhoa12pfiev3 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello.
I'm trying to use cassandra in ambari-server.
I installed ambari-server and some nodes on real machines instead of using HDPSandbox.
I'm using Ubuntu 16.04 as my OS. The version of cluster is HDP - 2.6.3.0
I followed your instructions to install cassandra. At the final step, the installation was failed because of this error of Cluster Nodes Install
Traceback (most recent call last):
File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/cassandra_master.py", line 60, in
Cassandra_Master().execute()
File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 367, in execute
method(env)
File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/CASSANDRA/package/scripts/cassandra_master.py", line 30, in install
self.install_packages(env)
File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 813, in install_packages
retry_count=agent_stack_retry_count)
File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 166, in init
self.env.run()
File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
self.run_action(resource, action)
File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
provider_action()
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/init.py", line 53, in action_install
self.install_package(package_name, self.resource.use_repos, self.resource.skip_repos)
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/apt.py", line 75, in wrapper
return function_to_decorate(self, name, *args[2:])
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/apt.py", line 376, in install_package
self.checked_call_with_retries(cmd, sudo=True, env=INSTALL_CMD_ENV, logoutput=self.get_logoutput())
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/init.py", line 251, in checked_call_with_retries
return self._call_with_retries(cmd, is_checked=True, **kwargs)
File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/init.py", line 268, in _call_with_retries
code, out = func(cmd, **kwargs)
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 72, in inner
result = function(command, **kwargs)
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 102, in checked_call
tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 150, in _call_wrapper
result = _call(command, **kwargs_copy)
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 303, in _call
raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21' returned 100. Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dsc21
stdout: /var/lib/ambari-agent/data/output-191.txt

2017-12-04 09:59:06,860 - Stack Feature Version Info: Cluster Stack=2.6, Command Stack=None, Command Version=None -> 2.6
2017-12-04 09:59:06,865 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-12-04 09:59:06,866 - Group['hdfs'] {}
2017-12-04 09:59:06,866 - Group['hadoop'] {}
2017-12-04 09:59:06,867 - Group['users'] {}
2017-12-04 09:59:06,867 - User['infra-solr'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,868 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,868 - User['cassandra'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,869 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,869 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users'], 'uid': None}
2017-12-04 09:59:06,870 - User['smoke'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,870 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hdfs'], 'uid': None}
2017-12-04 09:59:06,871 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,871 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop'], 'uid': None}
2017-12-04 09:59:06,872 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-12-04 09:59:06,873 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-12-04 09:59:06,876 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2017-12-04 09:59:06,877 - Group['hdfs'] {}
2017-12-04 09:59:06,877 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': ['hdfs', u'hdfs']}
2017-12-04 09:59:06,878 - FS Type:
2017-12-04 09:59:06,878 - Directory['/etc/hadoop'] {'mode': 0755}
2017-12-04 09:59:06,891 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-12-04 09:59:06,891 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2017-12-04 09:59:06,905 - Repository['HDP-2.6-repo-1'] {'append_to_file': False, 'base_url': 'http://public-repo-1.hortonworks.com/HDP/ubuntu16/2.x/updates/2.6.3.0', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': '{{package_type}} {{base_url}} {{components}}', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2017-12-04 09:59:06,912 - File['/tmp/tmp6cMkrY'] {'content': 'deb http://public-repo-1.hortonworks.com/HDP/ubuntu16/2.x/updates/2.6.3.0 HDP main'}
2017-12-04 09:59:06,912 - Writing File['/tmp/tmp6cMkrY'] because contents don't match
2017-12-04 09:59:06,912 - File['/tmp/tmpgvtRaA'] {'content': StaticFile('/etc/apt/sources.list.d/ambari-hdp-1.list')}
2017-12-04 09:59:06,913 - Writing File['/tmp/tmpgvtRaA'] because contents don't match
2017-12-04 09:59:06,913 - File['/etc/apt/sources.list.d/ambari-hdp-1.list'] {'content': StaticFile('/tmp/tmp6cMkrY')}
2017-12-04 09:59:06,913 - Writing File['/etc/apt/sources.list.d/ambari-hdp-1.list'] because contents don't match
2017-12-04 09:59:06,913 - checked_call[['apt-get', 'update', '-qq', '-o', u'Dir::Etc::sourcelist=sources.list.d/ambari-hdp-1.list', '-o', 'Dir::Etc::sourceparts=-', '-o', 'APT::Get::List-Cleanup=0']] {'sudo': True, 'quiet': False}
2017-12-04 09:59:07,040 - checked_call returned (0, '')
2017-12-04 09:59:07,041 - Repository['HDP-UTILS-1.1.0.21-repo-1'] {'append_to_file': True, 'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu16', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': '{{package_type}} {{base_url}} {{components}}', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2017-12-04 09:59:07,043 - File['/tmp/tmpPBUb6S'] {'content': 'deb http://public-repo-1.hortonworks.com/HDP/ubuntu16/2.x/updates/2.6.3.0 HDP main\ndeb http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu16 HDP-UTILS main'}
2017-12-04 09:59:07,043 - Writing File['/tmp/tmpPBUb6S'] because contents don't match
2017-12-04 09:59:07,044 - File['/tmp/tmpbGWklO'] {'content': StaticFile('/etc/apt/sources.list.d/ambari-hdp-1.list')}
2017-12-04 09:59:07,044 - Writing File['/tmp/tmpbGWklO'] because contents don't match
2017-12-04 09:59:07,044 - File['/etc/apt/sources.list.d/ambari-hdp-1.list'] {'content': StaticFile('/tmp/tmpPBUb6S')}
2017-12-04 09:59:07,044 - Writing File['/etc/apt/sources.list.d/ambari-hdp-1.list'] because contents don't match
2017-12-04 09:59:07,045 - checked_call[['apt-get', 'update', '-qq', '-o', u'Dir::Etc::sourcelist=sources.list.d/ambari-hdp-1.list', '-o', 'Dir::Etc::sourceparts=-', '-o', 'APT::Get::List-Cleanup=0']] {'sudo': True, 'quiet': False}
2017-12-04 09:59:07,178 - checked_call returned (0, 'W: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/ubuntu16/dists/HDP-UTILS/InRelease: Signature by key DF52ED4F7A3A5882C0994C66B9733A7A07513CAD uses weak digest algorithm (SHA1)')
2017-12-04 09:59:07,178 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,194 - Skipping installation of existing package unzip
2017-12-04 09:59:07,194 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,209 - Skipping installation of existing package curl
2017-12-04 09:59:07,209 - Package['hdp-select'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,224 - Skipping installation of existing package hdp-select
2017-12-04 09:59:07,228 - The repository with version 2.6.3.0-235 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2017-12-04 09:59:07,232 - Skipping stack-select on CASSANDRA because it does not exist in the stack-select package structure.
Install
2017-12-04 09:59:07,378 - Package['dsc21'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-12-04 09:59:07,394 - Installing package dsc21 ('/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21')
2017-12-04 09:59:08,682 - Execution of '/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install dsc21' returned 100. Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dsc21
2017-12-04 09:59:08,682 - Failed to install package dsc21. Executing '/usr/bin/apt-get update -qq'
2017-12-04 09:59:10,008 - Retrying to install package dsc21 after 30 seconds
2017-12-04 09:59:40,218 - The repository with version 2.6.3.0-235 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2017-12-04 09:59:40,223 - Skipping stack-select on CASSANDRA because it does not exist in the stack-select package structure.

Command failed after 1 tries

Can someone help me to fix it ?

**Comment by deweweb** [comment]
solution

https://www.ore.edu.pl/attachments/article/6993/Dokumentacja_administracyjno-programistyczna.pdf      '/etc/yum.repos.d/datastax.repo

http://codegists.com/code/install-apache-cassandra-centos/
######### Install Cassandra #############
cat > /etc/yum.repos.d/datastax.repo <<EOF
[datastax]
name = DataStax Repo for Apache Cassandra
baseurl = http://rpm.datastax.com/community
enabled = 1
gpgcheck = 0
EOF

**Comment by winnerineast** [comment]
@deweweb Sorry, I don't know the language in the pdf, can kindly help brief your solution? It sounds like install datastax separately.

**Comment by singh-abhijeet** [comment]
@ajak6 Please add reference to the artifacts (HDP `xml` file, yum `repo`) you mentioned.
